Saved images
christocarr/instagram-clone pull request #8
Opened 2021-08-16 08:23 UTC by christocarr

- add save button to modal to allow users to toggle a saved image
- add a custom hook to save image to local storage
- display saved images on saved page
- change modal to use react portal

2021-08-16 14:01 UTC, yoloOnTheBattlefield requested changes

2021-08-16 14:01 UTC, yoloOnTheBattlefield commented on src/components/Modal/Modal.js
> +      let diff = Math.abs(dateNow - dateCreated) / 1000;
any reason why you need a let here?

2021-08-16 14:01 UTC, yoloOnTheBattlefield commented on src/pages/Saved/Saved.js
> +import SaveImage from 'utils/SaveImage';
any reason why this PascalCase?

2021-08-16 14:01 UTC, yoloOnTheBattlefield commented on src/pages/SearchResults/SearchResults.js
> +import SaveImage from 'utils/SaveImage';
same here?

2021-08-16 14:01 UTC, yoloOnTheBattlefield commented on src/utils/useLocalStorage.js
> +// export default useLocalStorage;
no need for commented out code

2021-08-16 15:03 UTC, christocarr commented on src/pages/Saved/Saved.js
> +import SaveImage from 'utils/SaveImage';
![Screen Shot 2021-08-16 at 16 01 59](https://user-images.githubusercontent.com/22329677/129585242-b2cfdd95-3275-4c80-b49c-bf5dec30ecbd.png)

2021-08-17 11:44 UTC, yoloOnTheBattlefield approved these changes

2021-08-17 11:54 UTC, merged